baseurl: ""
url: "https://hellojames.co.uk"
title: hellojames
description: Hello, I&#39;m James. I&#39;m a design leader who helps organisations build great in-house teams and digital services.
plugins:
  - jekyll-redirect-from
