baseurl: ""
url: "https://hellojames.co.uk"
title: James Cook, Design Leader & Mentor • hellojamesSITE
description: I’m a design leader who helps organisations build great in-house teams and digital services. 20+ years’ experience delivering software systems, defining design practices, and developing people.


# match title & description to meta tags

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

include:
  - agents.txt
  - llms.txt
  - robots.txt
  - humans.txt

# exclude paths from jekyll-sitemap
defaults:
  - scope:
      path: "media"
    values:
      sitemap: false
  - scope:
      path: "writing/media"
    values:
      sitemap: false
